# Generated by Django 4.0.2 on 2022-02-16 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EquipmentIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=48)),
                ('department', models.CharField(max_length=48)),
                ('equipment', models.CharField(max_length=48)),
                ('serial_number', models.CharField(max_length=48)),
                ('status', models.TextField(blank=True)),
            ],
        ),
    ]
