# Generated by Django 4.0.2 on 2022-02-16 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipmentissue',
            name='descrption',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='equipmentissue',
            name='status',
            field=models.CharField(max_length=32),
        ),
    ]
