# Generated by Django 3.1.4 on 2022-02-19 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_equipmentissue_descrption_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipmentissue',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='equipmentissue',
            name='is_issue',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='equipmentissue',
            name='slug',
            field=models.SlugField(blank=True, max_length=48),
        ),
        migrations.AlterField(
            model_name='equipmentissue',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='ProductTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('slug', models.SlugField(blank=True, max_length=48)),
                ('description', models.TextField(blank=True)),
                ('active', models.BooleanField(default=True)),
                ('equipmentIssues', models.ManyToManyField(blank=True, to='main.EquipmentIssue')),
            ],
        ),
    ]
