# Generated by Django 3.1.4 on 2022-02-19 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20220219_2236'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductTag',
            new_name='EquipmentIssueTag',
        ),
    ]
