# Generated by Django 3.1.4 on 2022-02-19 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20220219_2314'),
    ]

    operations = [
        migrations.RenameField(
            model_name='equipmentissue',
            old_name='slug',
            new_name='issued_with',
        ),
        migrations.RenameField(
            model_name='equipmentissuetag',
            old_name='slug',
            new_name='issued_with',
        ),
    ]
