# Generated by Django 3.1.4 on 2022-02-19 23:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20220220_0113'),
    ]

    operations = [
        migrations.RenameField(
            model_name='equipmentissue',
            old_name='equipment',
            new_name='equipment_category',
        ),
    ]
