# Generated by Django 3.1.4 on 2022-04-09 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20220220_0121'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipmentissue',
            name='row',
            field=models.IntegerField(default=1),
        ),
    ]
