# Generated by Django 3.1.4 on 2022-04-11 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_remove_equipmentissue_row'),
    ]

    operations = [
        migrations.RenameField(
            model_name='equipmentissue',
            old_name='descrption',
            new_name='description',
        ),
    ]
